### ISSUE TITLE
关于API文档里参数说明

### ISSUE THREAD

**Issue by ThreeBearsDan** [sendcloud2013/sendcloud_docs#10]
参数说明中有必需这一列，值可以为  是  否  ＊，请问这个*代表什么意思？

**Comment by sendcloud2013** [comment]
您好：*代表这个参数可能别的参数覆盖或者忽略，举个栗子，比如发送的时候用户可以传入to参数，也可以传入xsmtp参数，此时to参数里面的收件人将会被忽略
