### ISSUE TITLE
python通过requests包发邮件携带的附件名称可以是中文吗？

### ISSUE THREAD

**Issue by EugeneLiu** [sendcloud2013/sendcloud_docs#13]
我使用python第三方requests包调用接口'http://api.sendcloud.net/apiv2/mail/sendtemplate'，发送带附件的模板邮件，发现一只返回405方法不支持错误码。如果英文附件名可以正常发送。

**Comment by sendcloud2013** [comment]
您好：用urllib.quote('测试.txt') 这种方式就可以，代码示例我们也已经更新了，感谢
