### ISSUE TITLE
关于使用Python发送邮件的脚本参数问题

### ISSUE THREAD

**Issue by grugway** [sendcloud2013/sendcloud_docs#14]
在你们文档给出的python发送邮件模板中有如下代码：

files = {
    "attachments": (urllib.parse.quote(display_filename_1), open(filename1, 'rb'), 'application/octet-stream')
}

这里我已经把它改成Python3了，我想问的是，urllib.parse.quote(display_filename_1) 这个参数是有什么用处的？ （原代码为：urllib.quote(display_filename_1)）

**Comment by sendcloud2013** [comment]
这个是最终附件显示的文件名
