### ISSUE TITLE
文档中增加 sendcloud4j

### ISSUE THREAD

**Issue by denger** [sendcloud2013/sendcloud_docs#6]
希望将 [sendcloud4j](https://github.com/denger/sendcloud4j) 作为代码示例中的 Java 库。

**Comment by sendcloud2013** [comment]
您好：非常感谢您的贡献，我们由于代码经常需要更新，参数也可能增加和改动，用sendcloud4j不方便我们维护发布，我们现在提供了sdk供用户直接使用，再次表示感谢
